"use client";
import {useMemo,useState} from "react";
import {BarChart3,BookOpen,Bot,ChevronDown,CircleDollarSign,Clock3,LayoutDashboard,Plus,Search,Settings,ShieldCheck,Target,TrendingDown,TrendingUp,Wallet,X} from "lucide-react";

type Trade={symbol:string;side:"Long"|"Short";pnl:number;strategy:string;session:string;date:string};
const seed:Trade[]=[{symbol:"XAUUSD",side:"Long",pnl:684,strategy:"Liquidity Sweep + FVG",session:"London",date:"Oct 05"},{symbol:"EURUSD",side:"Short",pnl:342,strategy:"BOS + Retest",session:"New York",date:"Oct 04"},{symbol:"BOOM500",side:"Long",pnl:-146,strategy:"FVG",session:"Asia",date:"Oct 04"},{symbol:"GBPUSD",side:"Short",pnl:290,strategy:"Liquidity Sweep",session:"London",date:"Oct 03"},{symbol:"CRASH500",side:"Short",pnl:-128,strategy:"BOS + Retest",session:"New York",date:"Oct 03"}];
const nav=["Dashboard","Journal","Analytics","AI Review"];
export default function Home(){
 const [active,setActive]=useState("Dashboard"),[trades,setTrades]=useState(seed),[query,setQuery]=useState(""),[modal,setModal]=useState(false),[symbol,setSymbol]=useState("XAUUSD"),[pnl,setPnl]=useState("250");
 const filtered=useMemo(()=>trades.filter(t=>t.symbol.toLowerCase().includes(query.toLowerCase())||t.strategy.toLowerCase().includes(query.toLowerCase())),[trades,query]);
 const net=trades.reduce((a,t)=>a+t.pnl,0),wins=trades.filter(t=>t.pnl>0).length,losses=trades.filter(t=>t.pnl<0).length,winRate=trades.length?Math.round(wins/trades.length*100):0,grossWin=trades.filter(t=>t.pnl>0).reduce((a,t)=>a+t.pnl,0),grossLoss=Math.abs(trades.filter(t=>t.pnl<0).reduce((a,t)=>a+t.pnl,0)),pf=grossLoss? (grossWin/grossLoss).toFixed(2):"—";
 const add=()=>{setTrades([{symbol:symbol.toUpperCase(),side:"Long",pnl:Number(pnl)||0,strategy:"Manual Entry",session:"Manual",date:"Today"},...trades]);setModal(false)};
 return <main className="shell"><aside className="sidebar"><div className="brand"><div className="brandMark">T</div><div><strong>TradeVault</strong><span>TRADING JOURNAL</span></div></div><div className="account"><div><span>Account</span><b>Demo Trading</b></div><ChevronDown size={16}/></div><nav>{nav.map(n=><button key={n} className={active===n?"navItem active":"navItem"} onClick={()=>setActive(n)}>{n==="Dashboard"?<LayoutDashboard/>:n==="Journal"?<BookOpen/>:n==="Analytics"?<BarChart3/>:<Bot/>}{n}</button>)}</nav><div className="sideBottom"><button className="navItem"><Settings/>Settings</button><div className="status"><ShieldCheck/><span><b>Journal sync</b>Ready for broker connection</span></div></div></aside>
 <section className="content"><header className="topbar"><div><p className="eyebrow">TRADING PERFORMANCE</p><h1>{active}</h1></div><button className="primary" onClick={()=>setModal(true)}><Plus/>Log trade</button></header>
 {active==="Dashboard"&&<Dashboard net={net} winRate={winRate} pf={pf} wins={wins} losses={losses} trades={trades}/>} {active==="Journal"&&<Journal query={query} setQuery={setQuery} trades={filtered} onAdd={()=>setModal(true)}/>} {active==="Analytics"&&<Analytics trades={trades}/>} {active==="AI Review"&&<AIReview trades={trades}/>}</section>
 {modal&&<div className="overlay"><div className="modal"><div className="modalHead"><div><p className="eyebrow">MANUAL ENTRY</p><h2>Log a trade</h2></div><button className="iconBtn" onClick={()=>setModal(false)}><X/></button></div><label>Symbol<input value={symbol} onChange={e=>setSymbol(e.target.value)}/></label><label>P&amp;L (USD)<input type="number" value={pnl} onChange={e=>setPnl(e.target.value)}/></label><button className="primary wide" onClick={add}>Save trade</button></div></div>}</main>;
}
function Metric({icon:Icon,label,value,detail}:{icon:any;label:string;value:string;detail:string}){return <div className="metric"><div className="metricIcon"><Icon/></div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>}
function Dashboard({net,winRate,pf,wins,losses,trades}:{net:number;winRate:number;pf:string;wins:number;losses:number;trades:Trade[]}){return <><div className="heroGrid"><Metric icon={CircleDollarSign} label="Net P&L" value={(net>=0?"+":"-")+"$"+Math.abs(net).toLocaleString()} detail="Across logged trades"/><Metric icon={Target} label="Win rate" value={winRate+"%"} detail={wins+" wins · "+losses+" losses"}/><Metric icon={TrendingUp} label="Profit factor" value={pf} detail="Gross profit ÷ gross loss"/><Metric icon={Wallet} label="Trades" value={String(trades.length)} detail="Manual / imported journal"/></div><div className="mainGrid"><section className="card chartCard"><div className="cardHead"><div><span className="label">EQUITY CURVE</span><h2>{net>=0?"+":"-"}${Math.abs(net).toLocaleString()} <small>net from logged trades</small></h2></div><select><option>Last 30 days</option></select></div><div className="chart"><div className="chartEmpty">Equity history will appear here after trades are connected.</div></div><div className="chartAxis"><span>Sep 06</span><span>Sep 20</span><span>Oct 05</span></div></section><section className="card"><div className="cardHead"><span className="label">SESSION EDGE</span><Clock3/></div>{["London","New York","Asia"].map(session=>{const ts=trades.filter(t=>t.session===session),p=ts.reduce((a,t)=>a+t.pnl,0);return <Session key={session} n={session} v={(p>=0?"+":"-")+"$"+Math.abs(p).toLocaleString()} p={ts.length+" "+(ts.length===1?"trade":"trades")}/>})}</section></div><section className="card recent"><div className="cardHead"><div><span className="label">RECENT TRADES</span><h2>Latest activity</h2></div><span className="muted">{trades.length} trades</span></div><TradeTable trades={trades.slice(0,5)}/></section></>}
function Session({n,v,p}:{n:string;v:string;p:string}){return <div className="session"><div><b>{n}</b><span>{v}</span></div><small>{p}</small></div>}
function Journal({query,setQuery,trades,onAdd}:{query:string;setQuery:(v:string)=>void;trades:Trade[];onAdd:()=>void}){return <section className="card full"><div className="journalToolbar"><div className="search"><Search/><input placeholder="Search symbols or strategies..." value={query} onChange={e=>setQuery(e.target.value)}/></div><button className="secondary" onClick={onAdd}><Plus/>Add trade</button></div><TradeTable trades={trades}/></section>}
function TradeTable({trades}:{trades:Trade[]}){return <div className="tableWrap"><table><thead><tr><th>TRADE</th><th>DIRECTION</th><th>P&amp;L</th><th>STRATEGY</th><th>SESSION</th></tr></thead><tbody>{trades.map((t,i)=><tr key={i}><td><b>{t.symbol}</b><small>{t.date}</small></td><td><span className={t.side==="Long"?"pill long":"pill short"}>{t.side}</span></td><td className={t.pnl>=0?"profit":"loss"}>{t.pnl>=0?"+":"-"}${Math.abs(t.pnl)}</td><td>{t.strategy}</td><td>{t.session}</td></tr>)}</tbody></table></div>}
function Analytics({trades}:{trades:Trade[]}){const names=[...new Set(trades.map(t=>t.strategy))];return <div className="analyticsGrid"><section className="card"><span className="label">BY STRATEGY</span>{names.map(s=>{const ts=trades.filter(t=>t.strategy===s),p=ts.reduce((a,t)=>a+t.pnl,0);return <div className="analyticRow" key={s}><div><b>{s}</b><small>{ts.length} trades</small></div><strong className={p>=0?"profit":"loss"}>{p>=0?"+":"-"}${Math.abs(p)}</strong></div>})}</section><section className="card"><span className="label">DIRECTIONAL BIAS</span><div className="bias">{["Long","Short"].map(side=>{const ts=trades.filter(t=>t.side===side),p=ts.reduce((a,t)=>a+t.pnl,0),pct=trades.length?Math.round(ts.length/trades.length*100):0;return <div key={side}>{side==="Long"?<TrendingUp/>:<TrendingDown/>}<b>{side}</b><strong className={p>=0?"profit":"loss"}>{p>=0?"+":"-"}${Math.abs(p)}</strong><small>{pct}% of trades · {ts.length} {ts.length===1?"trade":"trades"}</small></div>})}</div></section></div>}
function AIReview({trades}:{trades:Trade[]}){return <div className="aiPage"><section className="aiHero"><div className="aiIcon"><Bot/></div><div><span className="label">TRADEVAULT AI</span><h2>Your trading is strongest during London.</h2><p>TradeVault has {trades.length} logged trades. Connect or import real account history before drawing conclusions.</p></div></section><div className="insightGrid"><Insight title="Current sample" text={trades.length+" trades are available for analysis."}/><Insight title="No fabricated conclusions" text="The review engine will not call a setup your best strategy from a tiny sample."/><Insight title="Next input" text="Connect an account or import trade history to unlock meaningful reviews."/></div></div>}
function Insight({title,text}:{title:string;text:string}){return <div className="card insight"><div className="dot"/><div><b>{title}</b><p>{text}</p></div></div>}
